# Generated by Django 4.0.3 on 2022-04-09 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisment', '0003_alter_category_name_alter_offer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='advertisment.category'),
        ),
    ]
